ALTER TABLE customer
ADD COLUMN address_id BIGINT UNIQUE,
ADD COLUMN kyc_id BIGINT UNIQUE,
ADD CONSTRAINT fk_address FOREIGN KEY(address_id) REFERENCES address(id) ON DELETE CASCADE,
ADD CONSTRAINT fk_kyc FOREIGN KEY(kyc_id) REFERENCES kyc(id) ON DELETE CASCADE